name: Build Plugin Zip on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-plugin-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin source
        uses: actions/checkout@v4

      - name: Set plugin slug and zip name
        run: echo "PLUGIN_SLUG=gravity-folders" >> $GITHUB_ENV

      - name: Prepare plugin folder
        run: |
          mkdir -p build/$PLUGIN_SLUG
          shopt -s extglob
          cp -r !(build|.git|.github|.gitignore) build/$PLUGIN_SLUG

      - name: Zip plugin folder
        run: |
          cd build
          zip -r $PLUGIN_SLUG.zip $PLUGIN_SLUG

      - name: Upload plugin zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/gravity-folders.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
